### ISSUE TITLE
async issue

### ISSUE THREAD

**Issue by amelon** [dfellis/queue-flow#1]
Hi,

I've made some tests and found strange behaviors using async queue
With both following exemples, result is ok: "30"

```
q([0, 1, 2, 3, 4, 5])
  .map(function(val) {
    return val * 2;
  })
  .reduce(function(sum, cur) {
    return sum + cur;
  }, 'nextQueue', 0);

q('nextQueue').each(console.log);

// => result = 30

```

```
q([0, 1, 2, 3, 4, 5])
  .map(function(val, cb) {
    cb(val*2)
  })
  .reduce(function(sum, cur, cb) {
    cb(sum + cur);
  }, 'nextQueue', 0);

q('nextQueue').each(console.log);

// => result = 30
```

But with following exemple (async mimic), final result depends

```
q([0, 1, 2, 3, 4, 5])
  .map(function(val, cb) {
    setTimeout(function() { cb(val * 2) }, Math.random() * 100);
  })
  .reduce(function(sum, cur, cb) {
    cb(sum + cur);
  }, 'nextQueue', 0);

q('nextQueue').each(console.log);

// => result is sometimes 20, sometimes 22, rarely 30
```

And what is stranger is following queue exemple

```
q([0, 1, 2, 3, 4, 5])
  .each(console.log)
  .map(function(val, cb) {
    setTimeout(function() { cb(val * 2) }, Math.random() * 100);
  })
  .reduce(function(sum, cur, cb) {
    cb(sum + cur);
  }, 'nextQueue', 0);

q('nextQueue').each(console.log);

// => final result is always 0
```

Do I miss something?

**Comment by dfellis** [comment]
That is a bad regression. I'm adding these to the test file and I'll fix it. It appears to be related to automatically closing sub-queues if the initial queue was a static array (a feature that I haven't personally used in a while).

**Comment by dfellis** [comment]
It wasn't the automatically-closing of sub-queues (that was a side-effect), the issue was the internal `handlerCallback` wasn't keeping the queue-order intact for async queues if a previous queue fed results in faster than the async queue could process them. This is now in version 0.5.16
