### ISSUE TITLE
close event handler doesn't get triggered after a some call.

### ISSUE THREAD

**Issue by jingidy** [dfellis/queue-flow#10]
I'm using a close event handler to do cleanup after the queue finishes, but it's not getting called if I call 'some' somewhere in the queue. Below is the test code:

``` javascript
var q = require('queue-flow');

function broken (callback) {
  q([null])
  .node(function (args, cb) {
    console.log(1);
    cb(null, true);
  })
  .some(function (shouldContinue) { return shouldContinue; })
  .node(function (args, cb) {
    console.log(2);
    cb();
  })
  .on('close', function () {
    console.log('done');
    callback();
  });

}

broken(function () {
  console.log('That worked');
})
```

Expected output:

``` text
1
2
done
That worked
```

Actual output:

``` text
1
2
```

**Comment by dfellis** [comment]
I've added a slightly modified version of your test code, plus a few more test cases on the `every` and `some` methods (this affected both of them) and made sure that:
1. A continuing queue created by `every` or `some` is closed after the result is pushed in.
2. The result is properly compared versus the "polarity" (every value must match or at least one value must match) of the `everySome` method.

Published as 0.6.11
