### ISSUE TITLE
Named queues share scope

### ISSUE THREAD

**Issue by gmp** [dfellis/queue-flow#13]
While working on a fix on my end for the problem we saw in issue #12, I've noticed that named queues (which we are using for recursive purposes) are scoped globally and causing data to intermix.

See this gist https://gist.github.com/g-palmer/6927324 as an example of a test case I've created and the logged output I'm seeing.

Basically, I am calling the same function containing the named queues twice, in succession. Each call to the function is meant to run separately and uses different data and a different callback.

What I am seeing is that all of the data ends up merging together and only the second callback is ever called. Leaving our first call to the queue containing function hanging.

**Comment by dfellis** [comment]
So I started to fix that gist, but once I got it working it went into an infinite loop on the second scanAll because 'X' doesn't exist. Is that what you intended?

**Comment by dfellis** [comment]
https://gist.github.com/dfellis/6927599

**Comment by dfellis** [comment]
This is revealing a bug in the `.ns()` code, though. You ought to be able to do something like: `var localQ = q.ns();` and use that for scoping if your queue isn't actually a global element in your code, but that doesn't appear to be branching correctly.

**Comment by gmp** [comment]
Definitely not. That was simply meant as a flag in the test to continue the recurse branch a second time or switch to end. I can see now why that'd lead to the infinite loop when the queues become namespaced.

I've updated my gist to take care of that, and looks like following your example does namespace things correctlly - https://gist.github.com/g-palmer/6927324

**Comment by dfellis** [comment]
So that will help for now, but you're supposed to be able to use `q.ns()` to let you write the same style of code but with local namespacing, but `branch` is busted.

Once I have a fix on 0.6.x and 0.7.x for that I'll add the example code (forked off of your latest revision) and then close this issue.

**Comment by dfellis** [comment]
https://gist.github.com/dfellis/6928436

There. That's how you can construct a namespace for your queues and use the queue-flow API exactly the same as with the global queues. This works in 0.6.20 and 0.7.8.

**Comment by gmp** [comment]
Excellent. Thanks for being super responsive on this!

I think this should also solve our problem for #12 so we can likely close that as well.

**Comment by dfellis** [comment]
No problem! I'm sorry my tests didn't catch this much much earlier. Even 100% code coverage doesn't mean you're stressing that code in all of its possible permutations, unfortunately.

I've not had to use recursive queues in any of my "private" queues, so I've never run into this, unfortunately.

**Comment by dfellis** [comment]
Oh, and if #12 is fixed by this, go ahead and close that one out yourself. Otherwise give me another stack trace. :)
