### ISSUE TITLE
async each with no callback

### ISSUE THREAD

**Issue by amelon** [dfellis/queue-flow#2]
According to your tutorial, `each` should support callback argument in the callback function.

> each
> ...
> The signature of the callback function you provide should look like this: `function(value, [callback])`

But following exemple doesn't log what expected:

```
q([0, 1])
  .each(function(val, cb) {
    console.log('each', arguments);
  })
  .map(function(val, cb) {
    console.log('map', arguments);
    return 1;
  })

// => result is
// each { '0': 0 } => no function in arguments
// each { '0': 1 } => no function in arguments
// map { '0': 0, '1': [Function] } => ok
// map { '0': 1, '1': [Function] } => ok
```

**Comment by dfellis** [comment]
I've fixed this. I forgot that I rewrote `each` to no longer be built on top of `map`, so its async detection didn't carry over. This is now version 0.5.15
